### ISSUE TITLE
Vacuum cleaner socket error

### ISSUE THREAD

**Issue by StarT3** [stason325/node-red-contrib-miio-localdevices#37]
Hello.

While trying to add viomi.vacuum.v8 (no matter if it even exists, and i select viomi.vacuum.v7 as it shows in list) i'm getting such error:

_11 May 11:55:23 - [red] Uncaught Exception:
11 May 11:55:23 - [error] Error: getsockname EBADF
    at Socket.address (dgram.js:765:11)
    at Socket.<anonymous> (/root/.node-red/node_modules/node-mihome/lib/protocol-miio.js:34:36)
    at Socket.emit (events.js:412:35)
    at startListening (dgram.js:172:10)
    at dgram.js:364:7
    at processTicksAndRejections (internal/process/task_queues.js:83:21)_

node red 3.1.0 on CentOS7. Am i doing something wrong?

**Comment by kspgithub** [comment]
Hi!
Did you find any solution?
Faced a similar problem when adding yeelink.light.colorc

Previously added viomi.aircondition.y116 and had no problems, although both have miot-local support.

https://home.miot-spec.com/s/yeelink.light.colorc
https://home.miot-spec.com/s/viomi.aircondition.y116
